movieproject/movieapp/urls.py
from django.urls import path
from . import views

app_name = 'movieapp'
urlpatterns = [
    path('', views.index, name='index'),
    path('movie/<int:movie_id>/', views.detail, name='detail'),
    path('add/', views.add_movie, name='add_movie'),
    path('update/<int:id>/', views.update, name='update'),
    path('delete/<int:id>/', views.delete, name='delete'),
]

movieproject/movieproject/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("movieapp.urls")),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movieproject/movieapp/models.py
from django.db import models


# Create your models here.
class Movie(models.Model):
    name = models.CharField(max_length=250)
    desc = models.TextField()
    year = models.IntegerField()
    img = models.ImageField(upload_to='gallery')
    def __str__(self):
        return self.name

movieproject/movieapp/forms.py
from django import forms
from .models import Movie


class MovieForm(forms.ModelForm):
    class Meta:
        model = Movie
        fields = ['name', 'desc', 'year', 'img']

movieproject/movieapp/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from .models import Movie
from .forms import MovieForm


# Create your views here.
def index(request):
    movie = Movie.objects.all()
    context = {
        'movie_list': movie
    }
    return render(request, 'index.html', context)


def detail(request, movie_id):
    movie = Movie.objects.get(id=movie_id)
    return render(request, 'detail.html', {'movie': movie})


def add_movie(request):
    if request.method == "POST":
        name = request.POST.get('name', )
        desc = request.POST.get('desc', )
        year = request.POST.get('year', )
        img = request.FILES['img']
        movie = Movie(name=name, desc=desc, year=year, img=img,)
        movie.save()
    return render(request, 'add.html')


def update(request, id):
    movie = Movie.objects.get(id=id)
    form = MovieForm(request.POST or None, request.FILES, instance=movie)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request, 'edit.html', {'form': form, 'movie': movie})

def delete(request, id):
    if request.method=='POST':
        movie = Movie.objects.get(id=id)
        movie.delete()
        return redirect('/')
    return render(request, 'delete.html')

movieproject/templates/add.html
{% extends 'base.html' %}
{% block body %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="text" name="name" placeholder="Enter your Movie Name">
    <input type="text" name="desc" placeholder="Enter Movie Description">
    <input type="text" name="year" placeholder="Enter Movie release year">
    <input type="file" name="img">
    <input type="submit">
    {% endblock %}
</form>

movieproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'style.css' %}">

</head>
<body style="background-color:linen;">
<!--Hello-->
<!-- Image and text -->
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#">
    MOVEIT
  </a>
</nav>
{% block body %}
{% endblock %}
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

movieproject/templates/delete.html
<form method="POST">
    {% csrf_token %}
    Are you sure you want to delete this input?
    <input type="submit">
</form>

movieproject/templates/detail.html
{% extends 'base.html' %}
{% block body %}
<img src="{{movie.img.url}}" width="120" height="120">
{{movie.name}}<br>
{{movie.desc}}<br>
<strong>Year of Release:</strong><strong>{{movie.year}}</strong><br>
<a class="btn btn-warning" href="{% url 'movieapp:update' movie.id %}">Update</a>
<a class="btn btn-danger" href="{% url 'movieapp:delete' movie.id %}">Delete</a>
{% endblock %}

movieproject/templates/edit.html
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit">
</form>

movieproject/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
<!DOCTYPE html>
<html>
<head>

<style>
* {
  box-sizing: border-box;
}

.column {
  float: left;
  width: 33.33%;
  padding: 5px;
}

/* Clearfix (clear floats) */
.row::after {
  content: "";
  clear: both;
  display: table;
}
.body {
  font-family: Arial, Helvetica, sans-serif;
  font-size: 20px;
}

.center {
  display: block;
  margin-left: auto;
  margin-right: auto;
}

* {box-sizing: border-box;}
body {font-family: Verdana, sans-serif;}
.mySlides {display: none;}
img {vertical-align: middle;}

/* Slideshow container */
.slideshow-container {
  max-width: 1000px;
  position: relative;
  margin: auto;
}

/* Caption text */
.text {
  color: #f2f2f2;
  font-size: 15px;
  padding: 8px 12px;
  position: absolute;
  bottom: 8px;
  width: 100%;
  text-align: center;
}

/* Number text (1/3 etc) */
.numbertext {
  color: #f2f2f2;
  font-size: 12px;
  padding: 8px 12px;
  position: absolute;
  top: 0;
}

/* The dots/bullets/indicators */
.dot {
  height: 15px;
  width: 15px;
  margin: 0 2px;
  background-color: #bbb;
  border-radius: 50%;
  display: inline-block;
  transition: background-color 0.6s ease;
}

.active {
  background-color: #717171;
}

/* Fading animation */
.fade {
  animation-name: fade;
  animation-duration: 1.5s;
}

@keyframes fade {
  from {opacity: .4}
  to {opacity: 1}
}

/* On smaller screens, decrease text size */
@media only screen and (max-width: 300px) {
  .text {font-size: 11px}
}

</head>
</style>
<body>

<h2><strong>FILM INDUSTRY</strong></h2>
<p>The film industry or motion picture industry comprises the technological and commercial institutions of filmmaking, i.e., film production companies, film studios, cinematography, animation, film production, screenwriting, pre-production, post production, film festivals, distribution, and actors. Though the expense involved in making films almost immediately led film production to concentrate under the auspices of standing production companies, advances in affordable filmmaking equipment, as well as an expansion of opportunities to acquire investment capital from outside the film industry itself, have allowed independent film production to evolve.

In 2019, the global box office was worth $42.2 billion. When including box office and home entertainment revenue, the global film industry was worth $136 billion in 2018. Hollywood is the world's oldest [de facto] national film industry. However, in 2020, China became the largest box office territory, overtaking North America in gross total. The transition, long anticipated by analysts, was accelerated by the COVID-19 pandemic.Indian cinema is the largest national film industry in terms of the number of films produced, with 2,446 feature films produced annually as of 2019.As of 2019, Chinese cinema has the highest annual ticket sales with 1,650 million tickets sold.</p>
<br>

<br>

<div class="slideshow-container">

<div class="mySlides fade">
  <img src="{% static 'images/boxoffice.png' %}" style="width:1000px; height:300px;">
</div>

<div class="mySlides fade">
  <img src="{% static 'images/bollywood.jpg' %}" style="width:1000px; height:300px;">
</div>

<div class="mySlides fade">
  <img src="{% static 'images/hollywood.png' %}" style="width:1000px; height:300px;">
</div>

</div>
<br>

<div style="text-align:center">
  <span class="dot"></span>
  <span class="dot"></span>
  <span class="dot"></span>
</div>

<script>
let slideIndex = 0;
showSlides();

function showSlides() {
  let i;
  let slides = document.getElementsByClassName("mySlides");
  let dots = document.getElementsByClassName("dot");
  for (i = 0; i < slides.length; i++) {
    slides[i].style.display = "none";
  }
  slideIndex++;
  if (slideIndex > slides.length) {slideIndex = 1}
  for (i = 0; i < dots.length; i++) {
    dots[i].className = dots[i].className.replace(" active", "");
  }
  slides[slideIndex-1].style.display = "block";
  dots[slideIndex-1].className += " active";
  setTimeout(showSlides, 2000); // Change image every 2 seconds
}
</script>

<br>

<div class="container">
    <div class="row">
        {% for i in movie_list %}
        <div class="col-4 col-md-4">
            <div class="card h-100">
  <img src="{{i.img.url}}" class="card-img-top" alt="....." height="200px">
  <div class="card-body">
      <h5 class="card-title"><strong>{{i.name}}</strong></h5>
<!--    <p class="card-text">{{i.desc}}</p>-->
    <a href="{% url 'movieapp:detail' i.id %}" class="btn btn-primary">View Details</a>
  </div>
</div>
        </div>
        {% endfor %}
    </div>
</div>
    {% endblock %}
<!--    <meta name="viewport" content="width=device-width, initial-scale=1">-->